services:
  api:
    container_name: ytune-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: ytune-api:latest
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - CORS=${CORS}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - proxy_net
    healthcheck:
      test: >
        CMD-SHELL
        node -e "require('http').get('http://localhost:${PORT}/api/${VERSION}/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
networks:
  proxy_net:
    external: true
